apiVersion: alert.monstorak.org/v1alpha1
kind: CephAlert
metadata:
  name: example-cephalert
spec:
  # Add fields here
  size: 3
  storageName: ceph
  storageVersion: "3.10"
  storageAlert:
    enabled: true
    prometheusNamespace: "somenamespace"
  storageDashboard:
    enabled: false
    grafanaNamespace: "somegrafananamespace"
