apiVersion: alerts.monstorak.org/v1alpha1
kind: StorageAlert
metadata:
  name: monstorak-storagealert
  namespace: storage-monitoring
spec:
  size: 1
  storageType: "ceph"
  storageVersion: "v14"
  storageAlert:
    prometheusNamespace: "openshift-monitoring"
