apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monstorak
  namespace: storage-monitoring
  labels:
     app: monstorak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monstorak
  template:
    metadata:
      labels:
        app: monstorak
    spec:
      serviceAccountName: monstorak
      containers:
      - image: uchapaga/monstorak:82c43b9
        imagePullPolicy: Always
        name: monstorak
        env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "monstorak"
